# Generated by Django 5.1.4 on 2026-06-30 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('shiny', 'Shiny (bonus)'), ('cursed', 'Maudit (malus)')], max_length=16)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Ex: {"points": 250}')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Poste spécial',
                'verbose_name_plural': 'Postes spéciaux',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('last_day', models.DateField(help_text='Dernier jour : déclenche le multiplicateur extrême sur les corrections.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Piscine',
                'verbose_name_plural': 'Piscines',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Ex: logtime_low, kw_quoi_feur, bsq_eval', unique=True)),
                ('category', models.CharField(choices=[('gain', 'Gain'), ('loss', 'Perte'), ('event', 'Événement / IRL')], max_length=16)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Règle',
                'verbose_name_plural': 'Règles',
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit admin',
                'verbose_name_plural': 'Audit admin',
                'ordering': ('-at',),
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('login', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('coalition', models.CharField(blank=True, max_length=64)),
                ('rank_modifier', models.IntegerField(default=0, help_text="Décalage de rang manuel (ex: pénalité 'quoi sans feur' = perd 1 place).")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.pool')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
        migrations.CreateModel(
            name='CurlTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('endpoint', models.CharField(max_length=120)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('day', models.DateField(db_index=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appuser')),
            ],
            options={
                'verbose_name': 'Tracking curl',
                'verbose_name_plural': 'Tracking curl',
                'ordering': ('-requested_at',),
                'indexes': [models.Index(fields=['ip', 'day'], name='core_curltr_ip_fcb189_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('day_raw_points', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('day_coefficient', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('day_final_points', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cumulative_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('rules_fingerprint', models.CharField(blank=True, help_text="Hash des versions de règles utilisées (détection des jours 'dirty').", max_length=64)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.appuser')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.pool')),
            ],
            options={
                'verbose_name': 'Snapshot quotidien',
                'verbose_name_plural': 'Snapshots quotidiens',
                'ordering': ('-day', 'rank'),
                'unique_together': {('user', 'day')},
            },
        ),
        migrations.CreateModel(
            name='DailyCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('coefficient', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('is_weekend', models.BooleanField(default=False, help_text='Déclenche le coef pénalisant week-end.')),
                ('locked', models.BooleanField(default=False, help_text='True une fois le jour figé (snapshot fait).')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='core.pool')),
            ],
            options={
                'verbose_name': 'Coefficient journalier',
                'verbose_name_plural': 'Coefficients journaliers',
                'ordering': ('-day',),
                'unique_together': {('pool', 'day')},
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='logtime, exam, feedback_keyword, curl...', max_length=64)),
                ('source', models.CharField(choices=[('api_42', 'API 42'), ('web', 'Web (curl)'), ('manual', 'Manuel (staff)'), ('system', 'Système')], max_length=16)),
                ('occurred_at', models.DateTimeField(help_text='Horodatage métier (begin_at 42, etc.)')),
                ('event_date', models.DateField(db_index=True, help_text="Jour métier — clé d'agrégation des snapshots.")),
                ('rule_version', models.PositiveIntegerField(blank=True, help_text='Version EXACTE appliquée.', null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Données brutes API conservées.')),
                ('raw_points', models.DecimalField(decimal_places=2, default=0, help_text='Points AVANT coef journalier. Random DÉJÀ figé ici.', max_digits=14)),
                ('random_roll', models.JSONField(blank=True, help_text='Tirage figé (reproductibilité).', null=True)),
                ('dedup_key', models.CharField(blank=True, help_text="Clé d'idempotence pour le polling API (évite les doublons).", max_length=200, null=True, unique=True)),
                ('is_voided', models.BooleanField(default=False, help_text='Annulation logique (jamais de DELETE).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.appuser')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.pool')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rule')),
            ],
            options={
                'verbose_name': 'Événement (log)',
                'verbose_name_plural': 'Événements (log)',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['user', 'event_date'], name='core_eventl_user_id_d9e1c7_idx'), models.Index(fields=['pool', 'event_date'], name='core_eventl_pool_id_97f9d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('params', models.JSONField(default=dict, help_text='Ex: {"base": 100, "decay": "linear", "proba": 0.3, "multiplier": 1000}')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, help_text='NULL = version courante', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.rule')),
            ],
            options={
                'verbose_name': 'Version de règle',
                'verbose_name_plural': 'Versions de règles',
                'ordering': ('rule', '-version'),
                'unique_together': {('rule', 'version')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('status', models.CharField(choices=[('cursed', 'Maudit'), ('blessed', 'Béni')], max_length=16)),
                ('factor', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='core.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='core.appuser')),
            ],
            options={
                'verbose_name': 'Désignation hebdo',
                'verbose_name_plural': 'Désignations hebdo',
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
