# Generated by Django 5.1.4 on 2026-07-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycoefficient',
            options={'ordering': ('-day',), 'verbose_name': 'Jour de piscine', 'verbose_name_plural': 'Jours de piscine'},
        ),
    ]
