# Generated by Django 5.1.4 on 2026-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dailycoefficient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycoefficient',
            name='coef_event',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Multiplicateur des ÉVÉNEMENTS ce jour.', max_digits=8),
        ),
        migrations.AddField(
            model_name='dailycoefficient',
            name='coef_gain',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Multiplicateur des GAINS ce jour.', max_digits=8),
        ),
        migrations.AddField(
            model_name='dailycoefficient',
            name='coef_loss',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Multiplicateur des PERTES ce jour.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailycoefficient',
            name='coefficient',
            field=models.DecimalField(decimal_places=4, default=1, help_text='(hérité — non utilisé par le calcul par catégorie)', max_digits=8),
        ),
    ]
