# Generated by Django 5.1.4 on 2026-07-01 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailycoefficient_coef_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='mult_max',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='rule',
            name='mult_min',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.CreateModel(
            name='DailyEventMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('multiplier', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_multipliers', to='core.pool')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_multipliers', to='core.rule')),
            ],
            options={
                'verbose_name': 'Multiplicateur jour × event',
                'verbose_name_plural': 'Multiplicateurs jour × event',
                'ordering': ('-day', 'rule'),
                'unique_together': {('pool', 'day', 'rule')},
            },
        ),
    ]
