# Generated by Django 5.1.4 on 2026-07-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rule_mult_max_rule_mult_min_dailyeventmultiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('hostname', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('shiny', 'Bénite (Shiny)'), ('cursed', 'Maudite')], max_length=16)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_hosts', to='core.pool')),
            ],
            options={
                'verbose_name': 'Place du jour',
                'verbose_name_plural': 'Places du jour',
                'ordering': ('-day', 'kind', 'hostname'),
                'unique_together': {('pool', 'day', 'hostname')},
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=120)),
                ('last_seen', models.DateField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='core.pool')),
            ],
            options={
                'verbose_name': 'Poste (workstation)',
                'verbose_name_plural': 'Postes (workstations)',
                'unique_together': {('pool', 'hostname')},
            },
        ),
    ]
