# Generated by Django 5.1.4 on 2026-07-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_syncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Terminé'), ('error', 'Erreur'), ('cancelled', 'Annulé')], default='pending', max_length=12),
        ),
    ]
