# Generated by Django 5.1.4 on 2026-07-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seed_chaos_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='campus_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='cursus_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
