# Generated by Django 5.1.4 on 2026-07-04 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_midnight_bonus_logtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('status', models.CharField(choices=[('cursed', 'Maudit'), ('blessed', 'Béni')], max_length=8)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_designations', to='core.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_designations', to='core.appuser')),
            ],
            options={
                'verbose_name': 'Désignation du jour',
                'verbose_name_plural': 'Désignations du jour',
                'ordering': ('-day', 'status'),
                'unique_together': {('pool', 'user', 'day')},
            },
        ),
    ]
