# Generated by Django 5.1.4 on 2026-07-06 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rebalance_logtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolconfig',
            name='secret_board_chance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), help_text='Proba (0–1) du dedavid board à chaque curl. 0.01 = 1 %.', max_digits=5),
        ),
    ]
