# Generated by Django 5.1.4 on 2026-07-07 10:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_exam_rework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolconfig',
            name='plague_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('250'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='poolconfig',
            name='secret_board_chance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.003'), help_text='Proba (0–1) du dedavid board à chaque curl. 0.003 = 0,3 %.', max_digits=5),
        ),
    ]
