# Generated by Django 5.1.4 on 2026-07-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_unpunish_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Banni : tout mouvement de points (gain OU perte) devient une PERTE.'),
        ),
    ]
