# Generated by Django 5.1.4 on 2026-07-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_troll_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
