# Generated by Django 5.1.4 on 2026-07-13 08:37
"""
DailyPresence : marqueur factuel de présence, découplé du scoring (fix des
streaks d'assiduité — la présence était déduite des events assiduity_streak
eux-mêmes, chaîne auto-référentielle cassée par le moindre jour raté).

Backfill : la présence historique est reconstituée depuis TOUS les events de
la famille logtime/locations, VOIDÉS INCLUS — un event annulé (rework 0022,
agrégat réécrit…) prouve quand même que l'étudiant était là ce jour-là.
"""
import django.db.models.deletion
from django.db import migrations, models

# tout event de cette famille n'existe que si l'étudiant avait du logtime ce jour
_PRESENCE_EVENTS = ["assiduity_streak", "logtime_low", "logtime_high",
                    "logtime_minute", "midnight_bonus", "cluster_bonus",
                    "reconnect_same_pc"]


def backfill_presence(apps, schema_editor):
    EventLog = apps.get_model("core", "EventLog")
    AppUser = apps.get_model("core", "AppUser")
    DailyPresence = apps.get_model("core", "DailyPresence")
    # Dédupliqué par (user, jour) — un user peut avoir des events sous plusieurs
    # pools (démo + réelle) ; le pool CANONIQUE est celui de l'AppUser.
    pool_of = dict(AppUser.objects.values_list("id", "pool_id"))
    rows = {}
    for u, d in (EventLog.objects.filter(event_type__in=_PRESENCE_EVENTS)
                 .values_list("user_id", "event_date").distinct()):
        if u in pool_of:
            rows[(u, d)] = pool_of[u]
    DailyPresence.objects.bulk_create(
        [DailyPresence(pool_id=p, user_id=u, day=d) for (u, d), p in rows.items()],
        ignore_conflicts=True, batch_size=2000)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_syncrun_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.appuser')),
            ],
            options={
                'verbose_name': 'Présence quotidienne',
                'verbose_name_plural': 'Présences quotidiennes',
                'ordering': ('-day',),
                'unique_together': {('user', 'day')},
            },
        ),
        migrations.RunPython(backfill_presence, migrations.RunPython.noop),
    ]
