# Generated by Django 5.1.4 on 2026-07-20 12:16
"""
Docteurs 🩺 : soignent la Peste & le Choléra par correction, immunisés,
désignés manuellement au panel. Crée le modèle + seed les deux règles de
points associées (doctor_heal, patient_healed), éditables au panel.
"""
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

_NEW_RULES = ("doctor_heal", "patient_healed")


def seed_doctor_rules(apps, schema_editor):
    Rule = apps.get_model("core", "Rule")
    RuleVersion = apps.get_model("core", "RuleVersion")
    from core.rules_config import RULES, DEFAULT_MULT_MIN, DEFAULT_MULT_MAX
    now = timezone.now()
    for key, category, label, params in RULES:
        if key not in _NEW_RULES:
            continue
        rule, _ = Rule.objects.get_or_create(
            key=key, defaults={"category": category, "label": label,
                               "mult_min": DEFAULT_MULT_MIN, "mult_max": DEFAULT_MULT_MAX})
        if not rule.versions.exists():
            RuleVersion.objects.create(rule=rule, version=1, params=params, valid_from=now)


def unseed(apps, schema_editor):
    apps.get_model("core", "Rule").objects.filter(key__in=_NEW_RULES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_daily_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_roles', to='core.appuser')),
            ],
            options={
                'verbose_name': 'Docteur',
                'verbose_name_plural': 'Docteurs',
                'ordering': ('user__login',),
                'unique_together': {('pool', 'user')},
            },
        ),
        migrations.RunPython(seed_doctor_rules, unseed),
    ]
